import streamlit as st
from fpdf import FPDF
import random
import io

# --- 1. PDF 產出函數 (定義在最上方，避免縮排錯誤) ---
def generate_psi_pdf(age, height, weight, body_fat, total_score, diagnosis):
    pdf = FPDF()
    pdf.add_page()
    
    # 嘗試載入字型，若失敗則退回 Arial
    try:
        # 確保 msjh.ttc 已經從 Brian-car-ai 下載並上傳到本專案根目錄
        pdf.add_font('MSJH', '', 'msjh.ttc')
        pdf.set_font('MSJH', size=12)
        title_text = "PSI 派大星指數診斷報告"
        result_text = f"最終得分：{total_score}%"
        diag_label = "診斷結果："
    except:
        pdf.set_font("Arial", size=12)
        title_text = "PSI Diagnosis Report"
        result_text = f"Final Score: {total_score}%"
        diag_label = "Diagnosis: "

    pdf.cell(200, 10, txt=title_text, ln=True, align='C')
    pdf.ln(10)
    pdf.cell(200, 10, txt=f"Age: {age}", ln=True)
    pdf.cell(200, 10, txt=f"Height: {height} cm / Weight: {weight} kg", ln=True)
    pdf.cell(200, 10, txt=f"Body Fat: {body_fat}%", ln=True)
    pdf.cell(200, 10, txt=result_text, ln=True)
    pdf.ln(5)
    pdf.multi_cell(0, 10, txt=f"{diag_label} {diagnosis}")
    pdf.ln(10)
    pdf.set_font_size(10)
    pdf.cell(200, 10, txt="Generated by Brian Aerospace Data Lab", ln=True, align='R')
    
    return pdf.output()

# --- 2. 網頁設定與 Session State ---
st.set_page_config(page_title="PSI 指數 - 通用診斷版", page_icon="🧬")

if 'weights' not in st.session_state:
    # 為 10 題生成隨機權重，避免測試者預判
    st.session_state.weights = [random.sample([0, 5, 10], 3) for _ in range(10)]

st.title("🧬 PSI 派大星指數 (General Version)")
st.markdown("---")

# --- 3. 基礎數據輸入 ---
st.sidebar.header("👤 受測者基本資料")
# 預設值參考使用者數據：181cm/74kg/19.5%
age = st.sidebar.number_input("年齡", min_value=10, max_value=100, value=41)
height = st.sidebar.number_input("身高 (cm)", min_value=100, max_value=250, value=181)
weight = st.sidebar.number_input("體重 (kg)", min_value=30, max_value=200, value=74)
body_fat = st.sidebar.number_input("體脂率 (%)", min_value=5.0, max_value=50.0, value=19.5, step=0.1)

# --- 4. 診斷題目 ---
st.header("📝 認知與環境診斷")

questions = [
    ("1. 對於目前的職業現狀，你的思維是？", ["追求絕對穩定，風險越低越好", "在穩定中尋求自我價值的突破", "主動擁抱變動，視危機為槓桿"]),
    ("2. 關於下班後的閒暇時間利用？", ["主要用於娛樂放鬆、舒緩工作壓力", "隨意安排，看當天心情而定", "有系統地學習新技能或經營複利資產"]),
    ("3. 面對複雜且未知的技術問題時？", ["傾向交給專家處理，不深究底層邏輯", "嘗試理解基本原理，但遇到困難會停下", "運用底層邏輯拆解，直到徹底掌握關鍵"]),
    ("4. 你對目前生活環境的『危機感』程度？", ["非常安逸，覺得現狀可以維持一輩子", "偶爾感到焦慮，但不知行動方向", "具備強烈積極不適感，並轉化為具體產出"]),
    ("5. 關於個人財務思維？", ["沒有具體規劃，領薪水後隨意開支", "有儲蓄習慣，主要靠勞力換取報酬", "精算資產配置，致力於將消費轉化為資產"]),
    ("6. 社交圈的內容大多圍繞在？", ["抱怨政策、明星八卦或瑣碎日常", "生活情報分享、美食或一般娛樂", "財富增長、技術進步與哲學思考"]),
    ("7. 面對身體素質（體態/健康）的自我管理？", ["順其自然，不刻意節制", "有意識地管理，但缺乏數據化監控", "視體態為個人競爭力，嚴格數據化管理"]),
    ("8. 學習新知識的頻率與深度？", ["很久沒有讀完一整本專業書籍", "被動接受資訊碎片，隨看隨忘", "每天主動攝取高含金量知識並內化"]),
    ("9. 對於『時間』的認知？", ["時間是可以用來換取金錢或娛樂的資源", "覺得時間過得很快，但不清楚產出為何", "時間是生命中最珍貴的資產，極度排斥熵增"]),
    ("10. 如果現在失去穩定的薪水收入？", ["會陷入恐慌，因為缺乏其他生存技能", "雖然擔心，但應該能勉強支撐一段時間", "充滿信心，因為具備強大的市場競爭力"])
]

user_responses = []
with st.form("psi_form"):
    for i, (q_text, opts) in enumerate(questions):
        st.write(f"**{q_text}**")
        choice = st.radio(f"Select_{i}", opts, label_visibility="collapsed")
        user_responses.append(opts.index(choice))
    
    submitted = st.form_submit_button("執行數據分析並產生報告")

# --- 5. 結果計算與 PDF 下載 ---
if submitted:
    # 根據 Session State 中的隨機權重計算分數
    total_score = sum(st.session_state.weights[i][user_responses[i]] for i in range(10))
    
    st.divider()
    
    # 根據分數決定顏色
    if total_score <= 25:
        score_color = "#28a745"  # 綠色
        status_title = "【 航太級靈魂 】"
        shock_msg = "維持得很好，你目前依然掌控著自己的航太引擎。"
    elif total_score <= 50:
        score_color = "#ffc107"  # 黃色
        status_title = "【 認知生鏽預警 】"
        shock_msg = "警報：平庸感正在侵蝕你的神經，你快要變成派大星了！"
    else:
        score_color = "#dc3545"  # 紅色
        status_title = "【 深度海星狀態 】"
        shock_msg = "危險！你的大腦已進入靜態損壞，再不行動就真的變成了廢柴大叔！"

    # --- 醒目的巨大數字與標題 ---
    st.markdown(f"""
        <div style="text-align: center; padding: 20px; border: 5px solid {score_color}; border-radius: 15px;">
            <h2 style="color: {score_color}; margin-bottom: 0;">{status_title}</h2>
            <p style="font-size: 80px; font-weight: 800; color: {score_color}; margin: 0;">{total_score}%</p>
            <h3 style="color: #555;">派大星指數 (PSI)</h3>
            <hr style="border: 1px solid #ddd;">
            <p style="font-size: 24px; font-weight: bold; color: #333;">{shock_msg}</p>
        </div>
    """, unsafe_allow_html=True)
    
    st.markdown("---")

    # 診斷語句 (用於 PDF)
    diagnosis = f"{status_title} {shock_msg}"

    # 產出 PDF 內容
    pdf_bytes = generate_psi_pdf(age, height, weight, body_fat, total_score, diagnosis)
    
    # 下載按鈕也做醒目一點
    st.download_button(
        label="📥 點此領取你的『航太級診斷報告書』",
        data=bytes(pdf_bytes),
        file_name=f"PSI_Report_{age}.pdf",
        mime="application/pdf",
        use_container_width=True
    )
